### ISSUE TITLE
urls are not correctly processed

### ISSUE THREAD

**Issue by ewingrj** [jrief/django-sass-processor#116]
With the following directory structure:

![screen shot 2019-02-19 at 1 31 34 pm](https://user-images.githubusercontent.com/30963004/53048919-bdea8b80-344a-11e9-895d-637d515fa248.png)

I have a rule in `_bootstrap_startup_ui.scss` like:

```
background: $background-color url(../images/cover-bg-1.jpg) center;
```

`style.scss` imports `sass/_bootstrap_start_ui.scss`

after compilation & collectstatic, I end up with a single css file in `static/core/style.css` however the background url is still `url(../images/cover-bg-1.jpg)`. It would need to be `url(images/cover-bg-1.jpg)` to point to the correct location.

I'm not sure if this is a config issue or not?

Relevant `settings.py`:

```
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, 'static'))

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'mysite', 'admin_ui', 'build', 'static')]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

WHITENOISE_ROOT = os.path.join(BASE_DIR, 'mysite', 'admin_ui', 'build', 'root')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder'
]

SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(BASE_DIR, 'node_modules'),
]
```

**Comment by jrief** [comment]
I'm not sure about the rules for relative includes in the sass-compiler, therefore after looking at your sample, it might be that you have to write `url(../../images/cover-bg-1.jpg)` since `_bootstrap_startup_ui.scss` is two levels up.

Anyway, I prefer to specify include paths explicitly. You may use your `SASS_PROCESSOR_INCLUDE_DIRS` and rewrite the above to `url(core/images/cover-bg-1.jpg)`.
Otherwise extend `SASS_PROCESSOR_INCLUDE_DIRS`; these values are passed into the compiler directly.

**Comment by ewingrj** [comment]
so changing it to `url(images/cover-bg-1.jpg)` worked I guess relative urls are taken from the `static/app/` path. I didn't need to change `SASS_PROCESSOR_INCLUDE_DIRS` either.
