### ISSUE TITLE
Add support to CachedStaticFilesStorage

### ISSUE THREAD

**Issue by Barnalite** [jrief/django-sass-processor#37]
It would be great to support the CachedStaticFilesStorage

**Comment by jrief** [comment]
Could you please explain its benefits in this context.

**Comment by kbrownlees** [comment]
For me I use ManifestStaticFilesStorage for cache breaking, but since sass processor generates its own url the cache break cannot occur.

Would be good if the same logic as https://github.com/django/django/blob/master/django/templatetags/static.py#L111 could be applied? Then the storage still gets called and the correct cache broken url can be generated.

**Comment by jrief** [comment]
Thanks. I have to familiarize with it, so please be patient.

**Comment by pegler** [comment]
it looks like the change in v0.5.6 fixed this

**Comment by awartani** [comment]
I am using v0.5.7 and I have this issue, for more information please see:
https://stackoverflow.com/questions/9130555/django-static-files-versioning
https://mike.tig.as/blog/2011/12/22/django-14-first-thoughts-cachedstaticfilesstorage/

**Comment by jrief** [comment]
Please create a pull request or ask me directly to implement this feature. I currently have no use for it.

**Comment by bblanchon** [comment]
I'm using `ManifestStaticFilesStorage` with Django 2.1.1 and django-sass-processor 0.7.1.
As far as I can tell, everything works as expected 👍
