### ISSUE TITLE
Unable to locate file

### ISSUE THREAD

**Issue by DanielTate** [jrief/django-sass-processor#44]
I have the examples set up according to the guide but get Unable to locate file issues.

sass_src doesn't work in the template and whenever it's included it throws this error:

`Unable to locate file mysite/static/main.scss while rendering tag 'sass_src' in template`

I am trying to run this on a basic django_cms build

Possibly I am missing something that wasn't included in the readme

**Comment by AndreasBackx** [comment]
Could you post your `settings.py` file and your project folder structure? `sass_src` should work just like the `static` tag but it should be looking in the directories mentioned in the README.

**Comment by DanielTate** [comment]
@AndreasBackx see this question:
http://stackoverflow.com/questions/38862786/why-cant-django-see-my-static-files

Let me know if you need more info I'm happy to share.

**Comment by AndreasBackx** [comment]
Best to keep generated static files and your SCSS files separate because you don't want CSS files in your Git repo. So I would not set `SASS_PROCESSOR_ROOT` so that it defaults to `STATIC_ROOT`, django-sass-processor will automatically detect where it's at. We don't have some kind of `SASS_ROOT`, that might be for a different app though.

Also set the `SASS_PROCESSOR_INCLUDE_DIRS` to the `scss/` folder, otherwise you have to do the following in your SCSS files:
```sass
@import 'scss/something';
```

You have also set `STATICFILES_DIRS` to a list of directories that already are in `mysite/static/` so you don't need to include that in `sass_src`.
