### ISSUE TITLE
Adding a CONTRIBUTING.md

### ISSUE THREAD

**Issue by AndreasBackx** [jrief/django-sass-processor#47]
I noticed that in the project single and double quotes are used interchangeably.  (The majority is single quotes it seems.) This together with adding documentation would be beneficial to the project and I think we should start put all of this information in `CONTRIBUTING.md` so we and other can refer to it.

The choice for docstrings is [Numpy](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy) or [Google](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) style? I've always used the Google one, what do you think?

Then I would just say that the code has to conform with PEP8 but not with the max 80 character rule. Rather I would say conform with a ~90 char rule. I would love to refer you to [this talk](https://www.youtube.com/watch?v=wf-BqAjZb8M) from Raymond Hettinger about PEP8 that talks about this.

**Comment by jrief** [comment]
Hi @AndreasBackx ,
this may seem weird, but I'm using the quoting style formerly proposed by Douglas Crockford:
"Single quotes for internal strings and double quotes for strings readable by humans".
This can be a big advantage, whenever one has to search for strings visible in other natural languages.
You therefore might see statements in my code such as:

```
color = ChoiceField(choices=[('red', "Red"), ('green', "Green"), ('blue', "Blue")])
```
This of course also applies to docstrings:
```
def foo():
    """Do foo stuff"""
```

About the line length, I follow the guideline from Django, which allows 119 characters, but I use a soft limit of 100, which means that I try to stay below, if otherwise I would have to use a ``\`` character.

I fully agree, that this should be added to a contributing file.

**Comment by AndreasBackx** [comment]
Good to know that you use that quoting style. I don't really mind and will do what has been done in the past on the project. Mine were only suggestions in case there weren't any.

I would also suggest using isort for imports.

**Comment by AndreasBackx** [comment]
No `CONTRIBUTING.md` I guess?
