### ISSUE TITLE
compilescss does not support jinja2

### ISSUE THREAD

**Issue by AndreasBackx** [jrief/django-sass-processor#49]
I wanted to add support for the `compilescss` command because currently the command does not support jinja2. There have been a lot of changes in django-compressor's compress command which added support for jinja2 since the compilescss here was written based on that one. I think we/I should refactor the command and inherit from the compress command. This way we can follow the changes there. The current command on django-compressor is very messy, I think it's best to refactor that on their end first and then inherit it here, but add some changes so instead of compressing it would compile SCSS.

It might also be good to add to the readme that setting `SASS_PROCESSOR_ENABLED` is the only way to use Jinja2 with `DEBUG` set to `False`.

**Comment by jrief** [comment]
But then django-compressor becomes a hard dependency. Currently that's optional.

The most important feature now, are unit tests. When I started, I was in a real hurry and that project was not intended to become what it is now. Normally I add unit tests right from the beginning.

**Comment by AndreasBackx** [comment]
Currently the readme states:
> django-compressor is required only for offline compilation, when using the command manage.py compilescss.

Won't it still be 'optional' in the same way (only required for offline use)? We're currently importing it in `compilescss.py` anyhow.

**Comment by frostbtn** [comment]
@AndreasBackx I think I've added `--engine jinja2` switch [a year ago](https://github.com/jrief/django-sass-processor/commit/6abd0de00037a3b07f53cff966316c0b8e6da971) just "because it was easy". Is it not working anymore? (I'm not using **jinja2** at the moment but thinking about it).

And yeah, **django-compressor** is actually not a very good thing to depend on - they have history of making breaking changes in their code with no good reason (like #45, it's still open with no reaction from their side). Maybe the better idea is right opposite - remove this dependency altogether. Just copy their django template walker and be done with it?

**Comment by AndreasBackx** [comment]
@frostbtn it wasn't working for me. It's been about 2 weeks since I looked into it so I cannot really remember it. As I'm currently no longer using a Jinja2 environment, but am using django-jinja I cannot check what caused it. But in any case support for django-jinja should perhaps also be added.

I would still say that we should depend on it as most of our users would benefit from using django-compressor and are perhaps already using it like I am. We could always keep the version locked to a specific version in case of a breaking change and make it work later on. I doubt there are gonna be a lot of big breaking changes.

**Comment by jrief** [comment]
can we close this?

**Comment by AndreasBackx** [comment]
@jrief I'll give it a look the coming weeks. Currently pretty busy.

**Comment by AndreasBackx** [comment]
It's been a while since I looked at the django-compressor part of the code. But could you explain to me why we need the django-compressor? Can't we simply find all of the `scss` files and compile them so they're available or am I missing something here?

**Comment by jrief** [comment]
In some sense **django-compressor** and **libsass** are complementary indeed, since they both compress the CSS files. In addition to that, **django-compressor** concatenates all CSS files included by your HTML file.

Here I use Sekizai in combination with Compressor. For example:

```
{% load sekizai_tags %}
...
<head>
   ...
   {% render_block "css" postprocessor "compressor.contrib.sekizai.compress" %}
</head>
```

If you use SCSS files exclusively and if you use *only one* SCSS file per HTML file (you can use ``@import "...";`` to achieve the same effect), then compressor is redundant indeed.

**Comment by AndreasBackx** [comment]
Doesn't the following work?

```jinja
{% compress css %}
<link rel="stylesheet" href="{% sass_src 'one.scss' %}" type="text/css" charset="utf-8">
<link rel="stylesheet" href="{% sass_src 'two.scss' %}" type="text/css" charset="utf-8">
{% endcompress %}
```

**Comment by jrief** [comment]
Maybe? I only use django-compress in combination with django-sekizai, hence I don't know.
