### ISSUE TITLE
engine flag does not work

### ISSUE THREAD

**Issue by guidezpl** [jrief/django-sass-processor#80]
Running compilecss with the --engine jinja2 flag does not get detected

**Comment by jrief** [comment]
@AndreasBackx can you confirm this?

**Comment by AndreasBackx** [comment]
I'm currently on holiday till the 11th of February so I cannot really look into this too much. But I assume that it's because you are also passing `--engine django` and I remember how Django handles lists in the arguments is odd. It's tested with the Django command assertions that it works and I use it in my own CI pipeline with only `&& python project/manage.py compilescss --engine jinja2 -v 0` for a Docker image. I'd recommend trying `--engine django jinja2` instead of `--jinja django --engine jinja2`. Try some combinations on how Django handles lists in the arguments. Some more information would also be helpful.

**Comment by jrief** [comment]
@AndreasBackx did you have a look at this?

**Comment by AndreasBackx** [comment]
I'd love to get some more information from @guidezpl, but I'll look at it this week.

**Comment by jrief** [comment]
never mind, we can close this.

**Comment by andyhd** [comment]
This is still an issue.

In the code for the management command here: https://github.com/jrief/django-sass-processor/blob/e54f2c4ae3f8fb7b795060a208ad4f1fd50627fc/sass_processor/management/commands/compilescss.py#L140 the list of engines is constructed by getting the `engines` item from the `options` keyword arguments, but there is only an `engine` item, so the list will always be the default of `['django']`.

This code looks unfinished - even if the `engine` keyword argument is used, this value is a string, not a list. The `add_argument` call for the `engine` argument would need to be called with `action='append'` and `default=['django']`, to accept multiple `--engine` arguments.

I can provide a failing test and a fix in a PR, if required.

**Comment by jrief** [comment]
Yes, a pull request to fix this would be great!
