### ISSUE TITLE
Using auto-prefixer with django-sass-processor

### ISSUE THREAD

**Issue by jdewanwala** [jrief/django-sass-processor#81]
Hi Jacob,

I was wondering if there's a way to use a vendor/browser auto-prefixing utility like auto-prefixer with django-sass-processor?

If so, could you please let me know how to go about it?

Thanks.

**Comment by jrief** [comment]
Hi @jdewanwala ,
this would be a great opportunity for you, to review  this branch:
https://github.com/jrief/django-sass-processor/tree/postcss

If it works for you I will release version 0.6.

**Comment by jdewanwala** [comment]
It's not working for me.

So I followed these steps:
1. Installed:
```
sudo npm install -g npx
npm install postcss-cli autoprefixer
```

2. In settings.py added:
```
STATICFILES_DIRS = [ ... , ... , os.path.join(BASE_DIR, 'node_modules'),]
```

3. Upgraded django-sass-processor from 0.5.6 to 0.5.8 using:
```
pip install --upgrade git+https://github.com/jrief/django-sass-processor.git
```
See below:
```
django-appconf==1.0.2
django-compressor==2.2
django-sass-processor==0.5.8 
```

Please let me know if I am doing anything wrong or missing any steps.

Your help is appreciated, as always.

**Comment by jrief** [comment]
> Please let me know if I am doing anything wrong or missing any steps.

Yes, not telling me what error messages you get :)

I just retested on Python-2.7 and there was an issue. Just patched the code. Please retry with the latest version from branch https://github.com/jrief/django-sass-processor/tree/postcss 
If it fails, please dump the error messages.

**Comment by BigE** [comment]
I'm working with the [postcss](https://github.com/jrief/django-sass-processor/tree/postcss) branch, attempting to get auto-prefixing working and not having a lot of luck myself. I've got all the prerequisites setup, and I've even verified that npx is being run inside the script. However, once the css file is generated, none of the auto-prefix items show up in the generated output. There are no errors raised during execution of the npx command either, I added some debugging and verified that the npx command completes successfully. I went a step further and wrote the file out in its different stages... I found that after the postcss command runs, the only thing that changes is the sourcemap comment is removed from the CSS and nothing else really changes once npx is run.

Once everything is generated, I can manually run `npx postcss --use autoprefixer --no-map /path/to/generated/css/site.css` and it will output the css to stdout with the expected prefixes at this point. I don't know why it isn't working when it automatically generates the files, since the command is running correctly as far as I can tell. Is there any debugging I can add to help get more information?
 Thanks!

**Comment by jrief** [comment]
I just found and fixed this bug. Everything should work now.

**Comment by jrief** [comment]
@BigE @jdewanwala please retest. If everything works, I'll release version 0.6. Thanks for reporting.

**Comment by BigE** [comment]
@jrief thanks for the update, this is looking a lot better and I'm seeing the autoprefix in the generated CSS now! My only "want" at this point would be to somehow get the map file generated with the css for development purposes. It might work by letting postcss write things out to a temporary file and then reading them back in maybe? I'm not sure... just spitballing at this point. Thanks for the quick reply and fix!

**Comment by jrief** [comment]
> My only "want" at this point would be ...

as far as I have seen, postcss append the sourcemap to the generated file, if I remove the ``--no-map`` from the invocation of autoprefixer. If it's that what you want, I can make this configurable.

**Comment by AndreasBackx** [comment]
@jrief I'd make it configurable, but make it default to the value of `DEBUG` I'd say.

**Comment by BigE** [comment]
I 100% agree with configurable, defaulting to the value of DEBUG. Otherwise, everything is working great on my end!
